# Generated by Django 4.2.3 on 2023-09-01 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_image_image_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_data', models.FileField(upload_to='files/')),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
