# Generated by Django 4.2.3 on 2023-09-01 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_image_delete_filemodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='SaveToFavoriteModel',
        ),
    ]
