# Generated by Django 4.2.3 on 2023-09-02 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_rename_image_savetofavoritemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtsModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.TextField()),
                ('is_favorite', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductColorModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.CharField(max_length=1000)),
                ('gelato_uid', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductTypeModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.CharField(max_length=1000)),
                ('gelato_uid', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PromptsModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('total_arts', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.usermodel')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSubCategoryModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=1000)),
                ('gelato_uid', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.producttypemodel')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSizeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.productmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ProductOrientationModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.productmodel')),
            ],
        ),
        migrations.AddField(
            model_name='productmodel',
            name='product_sub_cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.productsubcategorymodel'),
        ),
        migrations.CreateModel(
            name='ProductImageModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.CharField(max_length=1000)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.productcolormodel')),
                ('orientation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.productorientationmodel')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.productmodel')),
                ('size', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.productsizemodel')),
            ],
        ),
        migrations.AddField(
            model_name='productcolormodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.productmodel'),
        ),
        migrations.CreateModel(
            name='OrdersModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('house_no', models.CharField(max_length=255)),
                ('street_address', models.CharField(max_length=255)),
                ('address_2', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('zip_code', models.CharField(max_length=20)),
                ('total_amount', models.IntegerField()),
                ('paid', models.IntegerField()),
                ('total_items', models.IntegerField()),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('delivered', 'Delivered'), ('canceled', 'Canceled')], max_length=20)),
                ('gelato_order_id', models.IntegerField()),
                ('notes', models.TextField()),
                ('order_placed_at', models.DateTimeField()),
                ('stripe_payment_id', models.IntegerField()),
                ('stripe_customer_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.usermodel')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItemsModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gelato_uid', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('is_active', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.artsmodel')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.ordersmodel')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.productmodel')),
                ('product_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.productcolormodel')),
                ('product_orientation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.productorientationmodel')),
                ('product_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.productsizemodel')),
                ('product_sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.productsubcategorymodel')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.producttypemodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.usermodel')),
            ],
        ),
        migrations.AddField(
            model_name='artsmodel',
            name='prompt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.promptsmodel'),
        ),
        migrations.AddField(
            model_name='artsmodel',
            name='share',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.artsmodel'),
        ),
        migrations.AddField(
            model_name='artsmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.usermodel'),
        ),
    ]
