# Generated by Django 4.2.3 on 2023-09-02 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_artsmodel_productcolormodel_productmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='is_email_verified',
            field=models.BooleanField(default=True),
        ),
    ]
