# Generated by Django 4.2.3 on 2023-09-05 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_usermodel_is_email_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
